num_blocks:
  value: 2
num_features:
  value: 64
lr:
  value: 0.0000001
weight_decay:
  value: 0.00001
epochs:
  value: 1000
batch_size:
  value: 16
batch_normalization:
  value: True
optimizer:
  value: Adam
