method: bayes
name: 'DilatedNet'
metric:
  name: val loss
  goal: minimize
parameters:
  lr:
    min: 0.00001
    max: 0.0002
  weight_decay:
    min: 0.0001
    max: 0.1
  optimizer:
    distribution: constant
    value: Adam
  epochs:
    distribution: constant
    value: 15
  batch_size:
    distribution: constant
    value: 4
